

GET https://4aiigi2iul.execute-api.eu-central-1.amazonaws.com/prod/spaces
###

GET https://4aiigi2iul.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=617800e3-112b-4a4e-b66b-628e692bc1d1
###


POST https://4aiigi2iul.execute-api.eu-central-1.amazonaws.com/prod/spaces
Content-Type: : application/json

{
    "location": "De Panne",
    "name": "opgroei stad"
}
###

PUT https://4aiigi2iul.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=617800e3-112b-4a4e-b66b-628e692bc1d1
Content-Type: : application/json

{
    "location": "Brugge"
}
###

DELETE https://4aiigi2iul.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=23609d75-76f5-4500-981a-9912e9200404
###